LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := consumerir.default
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := consumerir.c

LOCAL_SHARED_LIBRARIES := liblog libhardware

LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
